### ISSUE TITLE
Typo in nav (Environment Varibles)

### ISSUE THREAD

**Issue by colbycheeze** [storybooks/getstorybook.io#59]
![08c58e98a7448c0e0143337d1411f3c7 _screen 20shot 202017-01-02 20at 2012 41 27 20pm](https://cloud.githubusercontent.com/assets/8884298/21594543/4e922bec-d0e9-11e6-81dc-7284679bdf38.png)

**Comment by arunoda** [comment]
Fixed via https://github.com/storybooks/getstorybook.io/pull/60
